version: "3"

services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             daphne csv_gen_service.asgi:application --bind 0.0.0.0 --port 8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"

  celery:
    build: .
    command: celery -A csv_gen_service worker -l INFO -c 20
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    restart: unless-stopped
    image: "redis:latest"
    expose:
      - 6379
